/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora1;


/**
 *
 * @author ERICK
 */
public class Pantalla extends javax.swing.JFrame {
    
    private static final String HISTORIAL_FILE = "historial.txt"; // Nombre del archivo de historial


    int num1, num2;
    String operador;
    

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Visor = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        button7 = new java.awt.Button();
        button8 = new java.awt.Button();
        button9 = new java.awt.Button();
        button10 = new java.awt.Button();
        button11 = new java.awt.Button();
        button13 = new java.awt.Button();
        button14 = new java.awt.Button();
        button15 = new java.awt.Button();
        button16 = new java.awt.Button();
        button17 = new java.awt.Button();
        button12 = new java.awt.Button();
        button18 = new java.awt.Button();
        button19 = new java.awt.Button();
        button20 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_Visor.setBackground(new java.awt.Color(204, 204, 204));
        txt_Visor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Visor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_Visor.setOpaque(true);
        getContentPane().add(txt_Visor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 360, 50));

        button1.setBackground(new java.awt.Color(153, 153, 153));
        button1.setLabel("C");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 50, 50));

        button2.setBackground(new java.awt.Color(153, 153, 153));
        button2.setLabel("/");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 50, 50));

        button3.setBackground(new java.awt.Color(153, 153, 153));
        button3.setLabel("X");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        getContentPane().add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 50, 50));

        button4.setBackground(new java.awt.Color(153, 153, 153));
        button4.setLabel("-");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        getContentPane().add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 50, 50));

        button5.setBackground(new java.awt.Color(153, 153, 153));
        button5.setLabel("7");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        getContentPane().add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 50, 50));

        button6.setBackground(new java.awt.Color(153, 153, 153));
        button6.setLabel("8");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        getContentPane().add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 50, 50));

        button7.setBackground(new java.awt.Color(153, 153, 153));
        button7.setLabel("9");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        getContentPane().add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 50, 50));

        button8.setBackground(new java.awt.Color(153, 153, 153));
        button8.setLabel("+");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        getContentPane().add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 50, 130));

        button9.setBackground(new java.awt.Color(153, 153, 153));
        button9.setLabel("4");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        getContentPane().add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 50, 50));

        button10.setBackground(new java.awt.Color(153, 153, 153));
        button10.setLabel("5");
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });
        getContentPane().add(button10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 50, 50));

        button11.setBackground(new java.awt.Color(153, 153, 153));
        button11.setLabel("6");
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });
        getContentPane().add(button11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 50, 50));

        button13.setBackground(new java.awt.Color(153, 153, 153));
        button13.setLabel("1");
        button13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button13ActionPerformed(evt);
            }
        });
        getContentPane().add(button13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 50, 50));

        button14.setBackground(new java.awt.Color(153, 153, 153));
        button14.setLabel("2");
        button14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button14ActionPerformed(evt);
            }
        });
        getContentPane().add(button14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 50, 50));

        button15.setBackground(new java.awt.Color(153, 153, 153));
        button15.setLabel("3");
        button15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button15ActionPerformed(evt);
            }
        });
        getContentPane().add(button15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 50, 50));

        button16.setBackground(new java.awt.Color(153, 153, 153));
        button16.setLabel("=");
        button16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button16ActionPerformed(evt);
            }
        });
        getContentPane().add(button16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 50, 140));

        button17.setBackground(new java.awt.Color(153, 153, 153));
        button17.setLabel("0");
        button17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button17ActionPerformed(evt);
            }
        });
        getContentPane().add(button17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 50, 50));

        button12.setBackground(new java.awt.Color(153, 153, 153));
        button12.setLabel(".");
        button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button12ActionPerformed(evt);
            }
        });
        getContentPane().add(button12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 50, 50));

        button18.setBackground(new java.awt.Color(153, 153, 153));
        button18.setLabel("CE");
        button18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button18ActionPerformed(evt);
            }
        });
        getContentPane().add(button18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 50, 50));

        button19.setBackground(new java.awt.Color(153, 153, 153));
        button19.setLabel("Opcion");
        button19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button19ActionPerformed(evt);
            }
        });
        getContentPane().add(button19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        button20.setBackground(new java.awt.Color(153, 153, 153));
        button20.setLabel("Ayuda");
        button20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button20ActionPerformed(evt);
            }
        });
        getContentPane().add(button20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        txt_Visor.setText(txt_Visor.getText() + "7");
    }//GEN-LAST:event_button5ActionPerformed

    private void button13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button13ActionPerformed
        txt_Visor.setText(txt_Visor.getText() + "1");
    }//GEN-LAST:event_button13ActionPerformed

    private void button16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button16ActionPerformed
        num2 = Integer.parseInt(txt_Visor.getText());

        switch (operador) {
            case "+":
                txt_Visor.setText(Integer.toString(num1 + num2));
                break;
            case "-":
                txt_Visor.setText(Integer.toString(num1 - num2));
                break;
            case "/":
                txt_Visor.setText(Integer.toString(num1 / num2));
                break;
            case "*":
                txt_Visor.setText(Integer.toString(num1 * num2));
                break;
        }
    }//GEN-LAST:event_button16ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        txt_Visor.setText(txt_Visor.getText() + "8");
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        txt_Visor.setText(txt_Visor.getText() + "9");
    }//GEN-LAST:event_button7ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        txt_Visor.setText(txt_Visor.getText() + "4");
    }//GEN-LAST:event_button9ActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
        txt_Visor.setText(txt_Visor.getText() + "5");
    }//GEN-LAST:event_button10ActionPerformed

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
        txt_Visor.setText(txt_Visor.getText() + "6");
    }//GEN-LAST:event_button11ActionPerformed

    private void button14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button14ActionPerformed
        txt_Visor.setText(txt_Visor.getText() + "2");
    }//GEN-LAST:event_button14ActionPerformed

    private void button15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button15ActionPerformed
        txt_Visor.setText(txt_Visor.getText() + "3");
    }//GEN-LAST:event_button15ActionPerformed

    private void button17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button17ActionPerformed
        txt_Visor.setText(txt_Visor.getText() + "0");
    }//GEN-LAST:event_button17ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        String cadena;
        cadena = txt_Visor.getText();
        
        if (cadena.length()>0){
            cadena = cadena.substring(0,cadena.length()-1);
            txt_Visor.setText(cadena);
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        num1 = Integer.parseInt(txt_Visor.getText());
        operador = "/";
        txt_Visor.setText("");
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        num1 = Integer.parseInt(txt_Visor.getText());
        operador = "*";
        txt_Visor.setText("");
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        num1 = Integer.parseInt(txt_Visor.getText());
        operador = "-";
        txt_Visor.setText("");
    }//GEN-LAST:event_button4ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        num1 = Integer.parseInt(txt_Visor.getText());
        operador = "+";
        txt_Visor.setText("");
    }//GEN-LAST:event_button8ActionPerformed

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed
        String cadena;
        cadena = txt_Visor.getText();
        
        if (cadena.length()<=0){
            txt_Visor.setText("0.");
        }
        else{
            if(!ExistePunto(txt_Visor.getText())){
                txt_Visor.setText(txt_Visor.getText()+".");
               
            }
        }
    }//GEN-LAST:event_button12ActionPerformed

    private void button18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button18ActionPerformed
        txt_Visor.setText("");
    }//GEN-LAST:event_button18ActionPerformed

    private void button20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button20ActionPerformed
        // Manual de usuario como texto dentro del código                                        
    String manualUsuario = "Manual de Usuario:\n"
        + "1. Ingrese los números utilizando los botones.\n"
        + "2. Seleccione la operación que desea realizar (+, -, *, /).\n"
        + "3. Presione '=' para obtener el resultado.\n"
        + "4. Use 'C' para ir borrarndo dígito por digito.\n"
        + "5. Use 'CE' para borrar todo los digitos de una solo vez en el visor.\n"
        + "6. El botón 'Ayuda' muestra este manual de usuario.";
    
    javax.swing.JOptionPane.showMessageDialog(this, manualUsuario, "Manual de Usuario", javax.swing.JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_button20ActionPerformed

    private void button19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button19ActionPerformed
                                             
    // Crear el menú emergente
    javax.swing.JPopupMenu opcionesMenu = new javax.swing.JPopupMenu();

    // Crear la opción "Nuevo"
    javax.swing.JMenuItem nuevoMenuItem = new javax.swing.JMenuItem("Nuevo");
    nuevoMenuItem.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            // Reiniciar la calculadora
            txt_Visor.setText("");
            num1 = 0;
            num2 = 0;
            operador = "";
            // Registrar la operación "Nuevo" en la bitácora
            System.out.println("Operación 'Nuevo' registrada en la bitácora");
        }
    });

    // Crear la opción "Historial"
    javax.swing.JMenuItem historialMenuItem = new javax.swing.JMenuItem("Historial");
    historialMenuItem.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            // Mostrar historial de operaciones
            javax.swing.JOptionPane.showMessageDialog(null, "Historial de operaciones no implementado", "Historial", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    });

    // Añadir opciones al menú
    opcionesMenu.add(nuevoMenuItem);
    opcionesMenu.add(historialMenuItem);

    // Mostrar el menú de opciones en la ubicación del botón
    opcionesMenu.show(button19, button19.getWidth() / 2, button19.getHeight() / 2);

    }//GEN-LAST:event_button19ActionPerformed
    public static boolean ExistePunto(String cadena) {
        boolean resultado;
        resultado = false;
        
        for (int i = 0; i < cadena.length(); i++){
        if (cadena.substring(i,i+1).equals(".")){
            resultado = true;
            break;
            
        }
    }
        return resultado;
    }
    public static String OPeraciones(String Numero1, String Signo,String Numero2){
        Double  Total=0.0;
        String Resultado;
        
        if (Signo.equals("/")){
            Total=Double.parseDouble(Numero1)/Double.parseDouble(Numero2);
        }
        if (Signo.equals("*")){
            Total=Double.parseDouble(Numero1)*Double.parseDouble(Numero2);
        }
        if (Signo.equals("-")){
            Total=Double.parseDouble(Numero1)-Double.parseDouble(Numero2);
        }
        if (Signo.equals("+")){
            Total=Double.parseDouble(Numero1)+Double.parseDouble(Numero2);
        }
        
        Resultado= Total.toString();
        return Resultado;
    }
            
            /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button10;
    private java.awt.Button button11;
    private java.awt.Button button12;
    private java.awt.Button button13;
    private java.awt.Button button14;
    private java.awt.Button button15;
    private java.awt.Button button16;
    private java.awt.Button button17;
    private java.awt.Button button18;
    private java.awt.Button button19;
    private java.awt.Button button2;
    private java.awt.Button button20;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    private javax.swing.JLabel txt_Visor;
    // End of variables declaration//GEN-END:variables
}
